server:
  port: 80
  session:
    timeout: 7200

weixin:
  AppID: wxa81bf46877580748
  AppSecret: a9c8a9a3be48413cb1fddd0b299d9940

spring:
  messages:
    basename: i18n.login
  themleaf:
    cache: false